# Generated by Django 2.0 on 2019-11-21 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='auditoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('ubic', models.CharField(max_length=20)),
                ('level_risk', models.IntegerField()),
                ('init_date', models.DateField()),
                ('fini_date', models.DateField()),
                ('inform', models.FileField(upload_to='informes/')),
            ],
        ),
    ]
