# Generated by Django 2.0 on 2019-11-21 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='inform',
            field=models.FileField(upload_to='media/informes/'),
        ),
    ]
