# Generated by Django 2.0 on 2019-11-21 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auditoria', '0003_convocatoria'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='convocatoria',
            unique_together={('auditoria', 'auditoria')},
        ),
    ]
