# Generated by Django 2.0 on 2019-11-29 05:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Auditoria', '0004_auto_20191120_2137'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='convocatoria',
            unique_together={('auditoria', 'user')},
        ),
    ]
